# Generated by Django 5.0.1 on 2024-01-07 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.CharField(blank=True, max_length=4, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('follows', models.ManyToManyField(related_name='followed_by', to='blog.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
