# Generated by Django 5.0.1 on 2024-01-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='upload',
            new_name='profile_pic',
        ),
    ]
