# Generated by Django 4.2.5 on 2024-01-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
