# Generated by Django 4.2.5 on 2024-01-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
