# Generated by Django 4.2.5 on 2024-01-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
